name: Docker Image CI

on:
  push:
    tags:
      - '*'
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight on the first day of every month
  workflow_dispatch: # Allows manual triggering of the workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get git tag
        id: tag
        if: github.event_name == 'push' && github.ref_type == 'tag'
        uses: dawidd6/action-get-tag@v1
        continue-on-error: true # catch tag failure when triggered on schedule or manually
        with:
          strip_v: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the docker image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            joooostb/caddy-outline-ss-scratch:stable
            joooostb/caddy-outline-ss-scratch:${{ steps.tag.outputs.tag || 'latest' }}
            ghcr.io/joooostb/caddy-outline-ss-scratch:stable
            ghcr.io/joooostb/caddy-outline-ss-scratch:${{ steps.tag.outputs.tag || 'latest' }}
          build-args: |
            VERSION=v${{ steps.tag.outputs.tag || 'latest' }}